
name: CI

on:
  schedule:
  - cron: "0 11,23 * * 1-5"
  - cron: "0 9,23 * * 6"
  - cron: "0 4,23 * * 0"
  workflow_dispatch:

jobs:
  CI_check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: pull container
        run: |
          docker pull ghcr.io/neyagawarobocons/robo_env_container:latest
      - name: colcon build
        run: |
          docker run --workdir=/ros_ws \
          --volume=.:/ros_ws ghcr.io/neyagawarobocons/robo_env_container:latest \
          bash -c ". /opt/ros/humble/setup.bash && colcon build --continue-on-error"
